version: '3'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "curl http://localhost:11434/api/version"]  # Changement ici
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  systeacher:
    build: .
    container_name: systeacher
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./Sys:/app/Sys
    ports:
      - "8000:8000"
      - "8501:8501"
    restart: unless-stopped

volumes:
  ollama_data: