version: '3'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/ || exit 0"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

  systeacher:
    build: .
    container_name: systeacher
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./Sys:/app/Sys
    ports:
      - "8000:8000"
      - "8501:8501"
    restart: unless-stopped

volumes:
  ollama_data: